version: 2.1

executors:
  python-executor:
    working_directory: ~/speech_recognition
    docker:
      - image: circleci/python:3.8

commands:
  install-packages:
    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "env"

jobs:
  check-linting:
    executor: python-executor
    steps:
      - install-packages

      - run:
          name: Run black, isort
          command: |
            source env/bin/activate
            black --check speech_recognition tests
            isort speech_recognition tests

  run-test:
    executor: python-executor
    steps:
      - install-packages

      - run:
          name: Run Tests
          command: |
            source env/bin/activate
            pytest --cov-branch --cov speech_recognition

      - run:
          name: Upload coverage report
          command: |
            source env/bin/activate
            codecov

  run-test-train:
    executor: python-executor
    steps:
      - install-packages

      - run:
          name: Run Tests Train
          command: |
            source env/bin/activate
            pytest -m interferable tests/run/test_train.py

  run-test-evaluate:
    executor: python-executor
    steps:
      - install-packages

      - run:
          name: Run Tests Evaluate
          command: |
            source env/bin/activate
            pytest -m interferable tests/run/test_evaluate.py

  run-test-inference:
    executor: python-executor
    steps:
      - install-packages

      - run:
          name: Run Tests Inference
          command: |
            source env/bin/activate
            pytest -m interferable tests/run/test_inference.py

workflows:
  main:
    jobs:
      - run-test
      - run-test-train
      - run-test-evaluate
      - run-test-inference
      - check-linting
