# RNN Type: one of ['rnn', 'lstm', 'gru']
rnn_type: lstm
# Vocab Size
vocab_size: 16000
# Encoder Hidden Dimension
encoder_hidden_dim: 256
# Decoder Hidden Dimension
decoder_hidden_dim: 256
# Encoder Layers
num_encoder_layers: 3
# Decoder Layers
num_decoder_layers: 2
# Dropout Rate
dropout: 0.15
# Pad Token ID
pad_id: 0
