# Model Name
model_name: las
# RNN Type: one of ['rnn', 'lstm', 'gru']
rnn_type: lstm
# Vocab Size
vocab_size: 16000
# Encoder Hidden Dimension
encoder_hidden_dim: 512
# Decoder Hidden Dimension
decoder_hidden_dim: 512
# Encoder Layers
num_encoder_layers: 4
# Decoder Layers
num_decoder_layers: 2
# Dropout Rate
dropout: 0.15
# teacher forcing rate
teacher_forcing_rate: 0.99
# Pad Token ID
pad_id: 0
