# Vocab Size
vocab_size: 16000
# Encoder Hidden Dimension
encoder_hidden_dim: 1024
# Decoder Hidden Dimension
decoder_hidden_dim: 1024
# Encoder Layers
num_encoder_layers: 4
# Decoder Layers
num_decoder_layers: 2
# Dropout Rate
dropout: 0.15
# Pad Token ID
pad_id: 0
