# File Format ("pcm", "wav", "flac", "mp3")
file_format: flac
# Audio Sample rate
sample_rate: 16000
# Frame Length for STFT
frame_length: 320
# Frame Step for STFT
frame_step: 160
# FFT Length for STFT
fft_length: 320
# Number of Mel bins for mel-spectrogram
num_mel_bins: 80
# Lowest frequency for mel-spectrogram
lower_edge_hertz: 80.0
# Largest frequency for mel-spectrogram
upper_edge_hertz: 7600.0
# Max audio log mel spectrogram sequence length
max_audio_length: 2048
# Max token sequence length
max_token_length: 128
# Use delta and deltas accelerate
use_delta_accelerate: false
